### ISSUE TITLE
500 Server Error editing order.

### ISSUE THREAD

**Issue by rterbush** [DynamoMTL/spree_chimpy#21]
Attempting to access an order through the admin panel errors out with the following.

```
Started GET "/admin/orders/R781673870/edit" for 174.29.117.52 at 2013-06-18 07:02:57 -0600
Processing by Spree::Admin::OrdersController#edit as HTML
  Parameters: {"id"=>"R781673870"}
spree_chimpy: Attempting to remove order R781673870
spree_chimpy: Adding order R781673870
Completed 500 Internal Server Error in 1186ms

Hominid::APIError (<330> Category Ids must be integers, not "".):
  vendor/bundle/ruby/1.9.1/gems/hominid-3.0.5/lib/hominid/api.rb:35:in `rescue in method_missing'
  vendor/bundle/ruby/1.9.1/gems/hominid-3.0.5/lib/hominid/api.rb:32:in `method_missing'
  vendor/bundle/ruby/1.9.1/bundler/gems/spree_chimpy-d819392b5ea9/lib/spree/chimpy/interface/orders.rb:15:in `add'
  vendor/bundle/ruby/1.9.1/bundler/gems/spree_chimpy-d819392b5ea9/lib/spree/chimpy/interface/orders.rb:30:in `sync'
  vendor/bundle/ruby/1.9.1/bundler/gems/spree_chimpy-d819392b5ea9/lib/spree_chimpy.rb:101:in `perform'
  vendor/bundle/ruby/1.9.1/bundler/gems/spree_chimpy-d819392b5ea9/lib/spree_chimpy.rb:89:in `handle_event'
  vendor/bundle/ruby/1.9.1/bundler/gems/spree_chimpy-d819392b5ea9/lib/spree/chimpy/engine.rb:27:in `block (2 levels) in <class:Engine>'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications/fanout.rb:47:in `call'
```

**Comment by braidn** [comment]
Hey all! Going to close this due to age. Feel free to reopen if it is still an issue in your apps. Thanks again.
